#!/usr/bin/env python3
"""Static routing regression only; NOT native/widget/gameplay execution."""
from pathlib import Path
import unittest

SOURCE = (Path(__file__).resolve().parents[1] / 'battle/QuickSpellPanel.cpp').read_text()


def check_source(source):
    context = source[source.index('std::shared_ptr<BattleInterface> currentQuickSpellContext'):source.index('QuickSpellPanel::QuickSpellPanel')]
    getter = source[source.index('QuickSpellPanel::getSpells()'):source.index('void QuickSpellPanel::create()')]
    create = source[source.index('void QuickSpellPanel::create()'):source.index('void QuickSpellPanel::changeSelectedSpell')]
    selection = source[source.index('void QuickSpellPanel::changeSelectedSpell'):source.index('void QuickSpellPanel::show(')]
    assert 'if(!owner.curInt || !owner.curInt->cb)' in source
    assert source.index('if(!owner.curInt || !owner.curInt->cb)') < source.index('owner.getBattle()')
    assert 'battle && battle->getBattle() ? battle : nullptr' in source
    assert 'context.lock()' in context
    assert 'quickSpellBattle(*current) != original' in context
    assert 'hero->id != heroID' in context
    assert 'reservedSlots.push_back(configured)' in getter
    assert 'spellIds.push_back(admitted ? id : SpellID::NONE)' in getter
    assert 'spellIdsFromSetting.push_back(configured && admitted)' in getter
    assert 'reservedSlots[i]' in getter
    assert getter.index('spellAllowedByBattleRoster(*battle, availableSpellID)') < getter.index('availableSpellID.toSpell()')
    assert 'persistentStorage.write' not in getter + create
    assert 'buttonsIsAutoGenerated.clear()' in create
    assert '[this' not in create
    assert '[id, context, heroID]' in create
    assert '[i, context, heroID](SpellID spell)' in create
    assert 'spellAllowedByBattleRoster(*currentBattle, id)' in create
    assert create.index('spellAllowedByBattleRoster(*currentBattle, id)') < create.index('id.toSpell()->canBeCast')
    assert 'currentBattle->battleGetMyHero()' in create
    assert selection.index('currentQuickSpellContext(context, heroID)') < selection.index('persistentStorage.write')
    assert 'spellAllowedByBattleRoster(*battle, spell)' in selection
    assert selection.index('spellAllowedByBattleRoster(*battle, spell)') < selection.index('persistentStorage.write')
    assert 'i < 0 || i >= QUICKSPELL_SLOTS' in selection
    assert 'SpellID::decode(spellIdentifier)' in getter
    assert 'spell == SpellID::NONE ? "" : spell.toSpell()->getJsonKey()' in selection
    assert selection.index('spellAllowedByBattleRoster(*battle, spell)') < selection.index('spell.toSpell()->getJsonKey()')
    assert 'spell.toSpell()->identifier' not in selection
    assert 'spellAllowedByWorldRoster' not in source


class QuickSpellRoutingSourceTest(unittest.TestCase):
    def test_actual_source_contract(self):
        check_source(SOURCE)

    def test_discriminating_source_mutants(self):
        mutations = [
            ('spell.toSpell()->getJsonKey()', 'spell.toSpell()->identifier'),
            ('if(!owner.curInt || !owner.curInt->cb)', 'if(false)'),
            ('battle && battle->getBattle() ? battle : nullptr', 'battle'),
            ('quickSpellBattle(*current) != original', 'false'),
            ('hero->id != heroID', 'false'),
            ('reservedSlots[i]', 'false'),
            ('spellIds.push_back(admitted ? id : SpellID::NONE)', 'spellIds.push_back(id)'),
            ('spellIdsFromSetting.push_back(configured && admitted)', 'spellIdsFromSetting.push_back(configured)'),
            ('buttonsIsAutoGenerated.clear();', ''),
            ('[id, context, heroID]', '[this, id, hero]'),
            ('spellAllowedByBattleRoster(*currentBattle, id)', 'spellAllowedByWorldRoster(*currentBattle, id)'),
            ('spellAllowedByBattleRoster(*battle, spell)', 'spellAllowedByWorldRoster(*battle, spell)'),
        ]
        for before, after in mutations:
            with self.subTest(removed=before):
                self.assertIn(before, SOURCE)
                with self.assertRaises(AssertionError):
                    check_source(SOURCE.replace(before, after, 1))


if __name__ == '__main__':
    unittest.main()
