/*
 * QuickSpellPanel.cpp, part of VCMI engine
 *
 * Authors: listed in file AUTHORS in main folder
 *
 * License: GNU General Public License v2.0 or later
 * Full text of license available in license.txt file, in main folder
 *
 */
#include "StdInc.h"
#include "QuickSpellPanel.h"

#include "BattleFieldController.h"
#include "BattleInterface.h"
#include "BattleWindow.h"

#include "../GameEngine.h"
#include "../CPlayerInterface.h"
#include "events/InputHandler.h"
#include "../gui/WindowHandler.h"
#include "../widgets/Buttons.h"
#include "../widgets/GraphicalPrimitiveCanvas.h"
#include "../widgets/Images.h"
#include "../widgets/TextControls.h"
#include "../windows/CSpellWindow.h"

#include "../../lib/CConfigHandler.h"
#include "../../lib/GameLibrary.h"
#include "../../lib/battle/CPlayerBattleCallback.h"
#include "../../lib/json/JsonUtils.h"
#include "../../lib/mapObjects/CGHeroInstance.h"
#include "../../lib/spells/CSpellHandler.h"
#include "../../lib/spells/NewHorizonsSpellAvailability.h"
#include "../../lib/texts/CGeneralTextHandler.h"
#include "../../lib/texts/MetaString.h"
#include "../GameInstance.h"

namespace
{
std::shared_ptr<CPlayerBattleCallback> quickSpellBattle(BattleInterface & owner)
{
	if(!owner.curInt || !owner.curInt->cb)
		return nullptr;
	try
	{
		const auto battle = owner.getBattle();
		return battle && battle->getBattle() ? battle : nullptr;
	}
	catch(const std::runtime_error &)
	{
		// The callback registry may already have removed an ended battle.
		return nullptr;
	}
}

std::shared_ptr<BattleInterface> currentQuickSpellContext(const std::weak_ptr<CPlayerBattleCallback> & context, ObjectInstanceID heroID)
{
	const auto original = context.lock();
	const auto current = CPlayerInterface::battleInt;
	if(!original || !current || quickSpellBattle(*current) != original)
		return nullptr;
	const auto * hero = original->battleGetMyHero();
	if(!hero || hero->id != heroID)
		return nullptr;
	return current;
}
}

QuickSpellPanel::QuickSpellPanel(BattleInterface & owner)
	: CIntObject(0)
	, owner(owner)
{
	OBJECT_CONSTRUCTION;

	addUsedEvents(LCLICK | SHOW_POPUP | MOVE | INPUT_MODE_CHANGE);

	pos = Rect(0, 0, 52, 600);
	background = std::make_shared<CFilledTexture>(ImagePath::builtin("DIBOXBCK"), pos);
	rect = std::make_shared<TransparentFilledRectangle>(Rect(0, 0, pos.w + 1, pos.h + 1), ColorRGBA(0, 0, 0, 0), ColorRGBA(241, 216, 120, 255));

	create();
}

std::vector<std::tuple<SpellID, bool>> QuickSpellPanel::getSpells() const
{
	const auto battle = quickSpellBattle(owner);
	const auto * hero = battle ? battle->battleGetMyHero() : nullptr;
	std::vector<SpellID> spellIds;
	std::vector<bool> spellIdsFromSetting;
	std::vector<bool> reservedSlots;
	for(int i = 0; i < QUICKSPELL_SLOTS; i++)
	{
		std::string spellIdentifier = persistentStorage["quickSpell"][std::to_string(i)].String();
		SpellID id;
		try
		{
			id = SpellID::decode(spellIdentifier);
		}
		catch(const IdentifierResolutionException &)
		{
			id = SpellID::NONE;
		}
		const bool configured = id != SpellID::NONE;
		const bool admitted = battle && hero && newHorizonsMagic::spellAllowedByBattleRoster(*battle, id);
		// Preserve configured intent without exposing a spell excluded by this
		// saved battle. Do not overwrite its preference or autofill its slot.
		reservedSlots.push_back(configured);
		spellIds.push_back(admitted ? id : SpellID::NONE);
		spellIdsFromSetting.push_back(configured && admitted);
	}

	// autofill empty slots with spells if possible
	for(int i = 0; i < QUICKSPELL_SLOTS; i++)
	{
		if(!battle || !hero || reservedSlots[i] || spellIds[i] != SpellID::NONE)
			continue;

		for(const auto & availableSpellID : LIBRARY->spellh->getDefaultAllowed())
		{
			if(!newHorizonsMagic::spellAllowedByBattleRoster(*battle, availableSpellID))
				continue;
			const auto * availableSpell = availableSpellID.toSpell();
			if(!availableSpell->isAdventure() && !availableSpell->isCreatureAbility() && hero->canCastThisSpell(availableSpell) && !vstd::contains(spellIds, availableSpell->getId()))
			{
				spellIds[i] = availableSpell->getId();
				break;
			}
		}
	}

	std::vector<std::tuple<SpellID, bool>> ret;
	for(int i = 0; i < QUICKSPELL_SLOTS; i++)
		ret.push_back(std::make_tuple(spellIds[i], spellIdsFromSetting[i]));
	return ret;
}

void QuickSpellPanel::create()
{
	OBJECT_CONSTRUCTION;

	labels.clear();
	buttons.clear();
	buttonsDisabled.clear();
	buttonsIsAutoGenerated.clear();

	const auto battle = quickSpellBattle(owner);
	const auto * hero = battle ? battle->battleGetMyHero() : nullptr;
	if(!hero)
	{
		redraw();
		return;
	}

	const std::weak_ptr<CPlayerBattleCallback> context = battle;
	const auto heroID = hero->id;
	auto spells = getSpells();
	for(int i = 0; i < QUICKSPELL_SLOTS; i++)
	{
		SpellID id;
		bool fromSettings;
		std::tie(id, fromSettings) = spells[i];

		std::string hoverText;
		if(id.hasValue())
		{
			MetaString tooltip;
			tooltip.appendTextID("core.genrltxt.26");
			tooltip.replaceName(id);
			hoverText = tooltip.toString(&GAME->translator());
		}
		else
			hoverText = LIBRARY->generaltexth->translate("vcmi.battleWindow.quickSpell.emptySlot");

		const auto callback = [id, context, heroID]()
		{
			const auto current = currentQuickSpellContext(context, heroID);
			if(!current)
				return;
			const auto currentBattle = quickSpellBattle(*current);
			if(currentBattle && newHorizonsMagic::spellAllowedByBattleRoster(*currentBattle, id)
				&& id.toSpell()->canBeCast(currentBattle.get(), spells::Mode::HERO, currentBattle->battleGetMyHero()))
				current->castThisSpell(id);
		};

		auto button = std::make_shared<CButton>(Point(2, 7 + 50 * i), AnimationPath::builtin("spellint"), CButton::tooltip(hoverText), callback);
		button->setOverlay(std::make_shared<CAnimImage>(AnimationPath::builtin("spellint"), id != SpellID::NONE ? id.num + 1 : 0));
		button->addPopupCallback([i, context, heroID](){
			const auto current = currentQuickSpellContext(context, heroID);
			if(!current)
				return;
			const auto currentBattle = quickSpellBattle(*current);
			if(!currentBattle)
				return;
			ENGINE->input().hapticFeedback();
			ENGINE->windows().createAndPushWindow<CSpellWindow>(currentBattle->battleGetMyHero(), current->curInt.get(), true,
				[i, context, heroID](SpellID spell){ changeSelectedSpell(i, spell, context, heroID); });
		});

		if(fromSettings)
			buttonsIsAutoGenerated.push_back(std::make_shared<TransparentFilledRectangle>(Rect(45, 37 + 50 * i, 5, 5), Colors::ORANGE));

		if(!newHorizonsMagic::spellAllowedByBattleRoster(*battle, id) || !id.toSpell()->canBeCast(battle.get(), spells::Mode::HERO, hero))
		{
			buttonsDisabled.push_back(std::make_shared<TransparentFilledRectangle>(Rect(2, 7 + 50 * i, 48, 36), ColorRGBA(0, 0, 0, 172)));
		}
		if(ENGINE->input().getCurrentInputMode() == InputMode::KEYBOARD_AND_MOUSE)
			labels.push_back(std::make_shared<CLabel>(7, 10 + 50 * i, EFonts::FONT_TINY, ETextAlignment::TOPLEFT, Colors::WHITE, keyBindingsConfig["keyboard"]["battleSpellShortcut" + std::to_string(i)].String()));

		buttons.push_back(button);
	}

	redraw();
}

void QuickSpellPanel::changeSelectedSpell(int i, SpellID spell, std::weak_ptr<CPlayerBattleCallback> context, ObjectInstanceID heroID)
{
	// No panel/hero pointer capture: same-context panel recreation is valid,
	// but replacing the battle callback or hero invalidates the selection.
	const auto current = currentQuickSpellContext(context, heroID);
	if(!current || i < 0 || i >= QUICKSPELL_SLOTS)
		return;
	const auto battle = quickSpellBattle(*current);
	if(!battle || (spell != SpellID::NONE && !newHorizonsMagic::spellAllowedByBattleRoster(*battle, spell)))
		return;
	Settings configID = persistentStorage.write["quickSpell"][std::to_string(i)];
	configID->String() = spell == SpellID::NONE ? "" : spell.toSpell()->getJsonKey();

	for (auto battleWindow : ENGINE->windows().findWindows<BattleWindow>())
		battleWindow->updateQueue(); // also recreates quick spell panel, if exists
}

void QuickSpellPanel::show(Canvas & to)
{
	// the battlefield erases its own area every frame, so only a panel above it must repaint
	if(owner.fieldController && pos.intersectionTest(owner.fieldController->pos))
		showAll(to);
	CIntObject::show(to);
}

void QuickSpellPanel::inputModeChanged(InputMode modi)
{
	create();
	redraw();
}
