#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate curated module metadata from canonical settings; --check detects drift."""
import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    previews = parser.add_mutually_exclusive_group()
    previews.add_argument('--hero-preview-output', type=Path,
                          help='Write a separate hero-development preview only to a new path under build/; never overwrite the working module')
    previews.add_argument('--capability-preview-output', type=Path,
                          help='Write unactivated capability rules only into a separate new candidate under build/')
    previews.add_argument('--capability-only-control-output', type=Path,
                          help='Write a separate diagnostic with capabilities on and primary growth off; never mutate a live module')
    previews.add_argument('--mastery-preview-output', type=Path,
                          help='Write future Artillery mastery rules/texts only to a new candidate under build/; no live activation')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    def canonical(name):
        return json.loads((root / 'config' / name).read_text(encoding='utf-8'))

    settings = canonical('newHorizonsCombat.json')
    settings['magic'] = {'newHorizons': canonical('newHorizonsMagic.json')}
    settings['heroes'] = {'newHorizons': canonical('newHorizonsHeroes.json')}
    schools = canonical('newHorizonsSchools.json')
    skills = canonical('newHorizonsSkills.json')
    metadata = {
        'name': 'New Horizons',
        'description': 'Curated rules: three Orders (including targeted Focus Fire) and '
                       'six magic schools with six ranked school skills. Existing hero spells '
                       'are reclassified; Sorcery Magic Arrow remains a level 1 spell and now '
                       'supports the saved Overcharge-ready direct-damage formula (base 20, '
                       'power coefficient 20). Faction Skills are assigned to every new hero '
                       'from its faction; Magic heroes replace Wisdom and Might heroes preserve '
                       'their class signature while replacing an optional starting skill. '
                       'Transfigure Matter is registered as the first '
                       'functional new spell; the remaining planned new spell roster, including '
                       'Magic Missile, is not registered. '
                       'Provisional coefficients, costs and flagged faction assignments. '
                       'New games snapshot rules; legacy saves retain their original semantics. '
                       'Generated by tools/update-new-horizons-module.py from canonical '
                       'config/newHorizons*.json data.',
        'modType': 'Mechanics',
        'version': '0.3.0',
        'author': 'New Horizons contributors',
        'licenseName': 'GPL-2.0-or-later; original artwork CC0-1.0',
        'licenseURL': 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html',
        'depends': ['vcmi'],
        'keepDisabled': False,
        # Named-file settings use the module's own filesystem, not core's config.
        # Inline generated settings preserve one authoring source without changing
        # that isolation or relying on an unmounted core file reference.
        'settings': settings,
        'spells': ['config/spells/newHorizons.json'],
        'spellSchools': schools,
        'skills': skills,
        'filesystem': {'SPRITES/': [{'type': 'dir', 'path': '/Images'}]},
    }
    metadata['description'] += (' Separate future development candidate: provisional class primary profiles, '
                                'scaled hero formulas and skill-related extra growth. '
                                'Not the frozen commands/schools release or full mastery/tier implementation.')
    destination = root / 'Mods/new-horizons/mod.json'
    preview_output = args.mastery_preview_output or args.capability_only_control_output or args.capability_preview_output or args.hero_preview_output
    if preview_output is not None:
        destination = preview_output.resolve()
        if not destination.is_relative_to((root / 'build').resolve()):
            parser.error('Hero preview output must be under the ignored build/ tree')
        if destination.exists() and not args.check:
            parser.error('Refusing to replace an existing preview; preserve frozen candidates')
    if args.hero_preview_output is None:
        settings['heroes']['newHorizonsCapabilities'] = canonical('newHorizonsCapabilities.json')
        metadata['version'] = '0.4.0'
        metadata['description'] += (' Separate capability candidate: non-destructive soft leadership capacity '
                                    'and skill-trained ballista scaling. No mastery or creature-category implementation.')
    if args.capability_only_control_output is not None:
        settings['heroes']['newHorizons'] = {}
        metadata['name'] = 'New Horizons (capability-only diagnostic)'
        metadata['description'] += (' DIAGNOSTIC ONLY: primary growth is disabled; authored primary values remain. '
                                    'This separate control is for ordinary saved-identity/UI testing, not a release preset.')
    if args.mastery_preview_output is not None or preview_output is None:
        settings['heroes']['newHorizonsMasteries'] = canonical('newHorizonsMasteries.json')
        metadata['translations'] = canonical('newHorizonsMasteryTexts.json')
        metadata['version'] = '0.5.0'
        metadata['description'] += (' Separate future Artillery mastery candidate: one permanent extra choice '
                                    'after a level gained with prior Expert Artillery. Not secondary rank four '
                                    'or completion of other mastery families, creature tiers or new spell effects.')
    if preview_output is None:
        # Default edition matches the active Magic Arrow v2 composition and
        # carries the canonical planned perk registry for saved runtime identity.
        # Explicit historical preview/control branches retain their own identities.
        settings['heroes']['newHorizonsPerks'] = canonical('newHorizonsPerks.json')
        metadata['version'] = '0.7.0'
        metadata['bonuses'] = canonical('newHorizonsConvenienceBonuses.json')
        metadata['filesystem'][''] = [{'type': 'dir', 'path': '/Content'}]
        metadata['description'] += (' Includes the canonical 31-Skill, ten-perk registry as planned data; '
                                    'perk selection and effects require the corresponding runtime systems. '
                                    'Includes independently authored quick-save/load buttons and creature ability '
                                    'icons; landscape presentation only.')
    expected = json.dumps(metadata, indent='\t', ensure_ascii=False) + '\n'
    if args.check:
        if not destination.is_file() or destination.read_text(encoding='utf-8') != expected:
            parser.exit(1, 'Curated module metadata is stale; run tools/update-new-horizons-module.py\n')
        print('PASS: module settings, six schools, 31 Skill entities, planned perk registry, image mount and metadata match canonical data')
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(expected, encoding='utf-8')
        print('Updated ' + str(destination.relative_to(root)))


if __name__ == '__main__':
    main()
